version: '3'

services:
  db-mongo:
    image: mongo:4.2.3
    ports:
      - 27017:27017
    networks:
      - git-tix-net
    volumes:
      - git-tix-vol:/data/db

networks:
  git-tix-net:
    driver: bridge

volumes:
  git-tix-vol:
    driver: local