apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: pramindanata/tix-auth
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: 'development'
            - name: APP_PORT
              value: '4000'
            - name: APP_USE_HTTPS
              value: 'false'
            - name: DB_HOST
              value: 'mongodb://auth-mongo-cluster-ip'
            - name: DB_NAME
              value: 'auth'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: auth-service
  ports:
    - name: auth-service
      protocol: TCP
      port: 4000
      targetPort: 4000