apiVersion: apps/v1
kind: Deployment
metadata:
  name: client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
        - name: client
          image: pramindanata/tix-client
          ports:
            - containerPort: 3000
          env:
            - name: APP_PORT
              value: '3000'
            - name: NEXT_PUBLIC_HOST
              value: 'git-tix.dev'
            - name: NEXT_PUBLIC_PROXY_HOST
              value: 'http://ingress-nginx-controller.ingress-nginx.svc.cluster.local'
            - name: NEXT_PUBLIC_STRIPE_PUB_KEY
              valueFrom:  
                secretKeyRef:
                  name: stripe-key
                  key: STRIPE_PUBLISH_KEY
---
apiVersion: v1
kind: Service
metadata:
  name: client-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: client
  ports:
    - name: client
      protocol: TCP
      port: 3000
      targetPort: 3000