apiVersion: apps/v1
kind: Deployment
metadata:
  name: expiration-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: expiration-service
  template:
    metadata:
      labels:
        app: expiration-service
    spec:
      containers:
        - name: expiration-service
          image: pramindanata/tix-expiration
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: 'development'
            - name: STAN_CLUSTER_ID
              value: 'git-tix'
            - name: STAN_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STAN_URL
              value: 'http://stan-cluster-ip:4222'
            - name: REDIS_HOST
              value: expiration-redis-cluster-ip
            - name: REDIS_PORT
              value: '6379'