apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
        - name: payment-service
          image: pramindanata/tix-payment
          ports:
            - containerPort: 4000
          env:
            - name: NODE_ENV
              value: 'development'
            - name: APP_PORT
              value: '4000'
            - name: APP_USE_HTTPS
              value: 'true'
            - name: DB_HOST
              value: 'mongodb://payment-mongo-cluster-ip'
            - name: DB_NAME
              value: 'payment'
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: STAN_CLUSTER_ID
              value: 'git-tix'
            - name: STAN_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: STAN_URL
              value: 'http://stan-cluster-ip:4222'
            - name: STRIPE_SECRET
              valueFrom:  
                secretKeyRef:
                  name: stripe-secret
                  key: STRIPE_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: payment-service
  ports:
    - name: payment-service
      protocol: TCP
      port: 4000
      targetPort: 4000