version: '3'

networks:
  kong-net:
    driver: bridge
  
volumes:
  kong-db:
    driver: local

services:
  db:
    container_name: kong-db
    image: postgres:11-alpine
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
      - TZ=Asia/Makassar
      - PGTZ=Asia/Makassar
    ports:
      - 5432:5432
    restart: always
    networks: 
      - kong-net
    volumes: 
      - kong-db:/var/lib/postgresql/data

  kong-migrations:
    container_name: kong-migration
    image: kong:2.1.3-alpine
    command: kong migrations bootstrap
    depends_on:
      - db
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    restart: on-failure
    networks:
      - kong-net

  kong-migrations-up:
    container_name: kong-migration-up
    image: kong:2.1.3-alpine
    command: kong migrations up && kong migrations finish
    depends_on:
      - db
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
    restart: on-failure
    networks:
      - kong-net

  kong-gateway:
    container_name: kong-gateway
    image: kong:2.1.3-alpine
    depends_on:
      - db
    ports:
      - 8500:8000
      - 8501:8001
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-db
      - KONG_PG_DATABASE=kong
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001
    restart: always
    networks:
      - kong-net

  konga:
    container_name: konga
    image: pantsel/konga:latest
    depends_on:
      - db
      - kong-gateway
    ports:
      - 1337:1337
    environment:
      - DB_ADAPTER=postgres
      - DB_HOST=kong-db
      - DB_PORT=5432
      - DB_USER=kong
      - DB_PASSWORD=kong
      - DB_DATABASE=kong
    restart: always
    networks:
      - kong-net