apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: pramindanata/tix-auth
          ports:
            - containerPort: 4000
          env:
            - name: APP_PORT
              value: '4000'
            - name: DB_HOST
              value: 'mongodb://auth-mongo-cluster-ip'
            - name: DB_NAME
              value: 'auth'
---
apiVersion: v1
kind: Service
metadata:
  name: auth-cluster-ip
spec:
  type: ClusterIP
  selector:
    app: auth
  ports:
    - name: auth
      protocol: TCP
      port: 4000
      targetPort: 4000