name: deploy-order

on:
  push:
    branches:
      - master
    paths:
      - 'packages/order/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}
      - run: |
          cd packages/order && docker build -t pramindanata/tix-order .
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
          docker push pramindanata/tix-order
          doctl kubernetes cluster kubeconfig save git-tix
          kubectl rollout restart deployment order-service
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    