name: deploy-manifest

on:
  push:
    branches:
      - master
    paths:
      - 'packages/infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}
      - run: doctl kubernetes cluster kubeconfig save git-tix
      - run: kubectl apply -f packages/infra/k8s

    