name: deploy-ticket

on:
  push:
    branches:
      - master
    paths:
      - 'packages/ticket/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DO_API_TOKEN }}
      - run: | 
          cd packages/ticket && docker build -t pramindanata/tix-ticket .
          echo "$DOCKER_PASSWORD" | docker login -u $DOCKER_USERNAME --password-stdin
          docker push pramindanata/tix-ticket
          doctl kubernetes cluster kubeconfig save git-tix
          kubectl rollout restart deployment ticket-service
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}

    